export const item = {
  title: 'ASCD Annual Reports',
  twoColContentListBody: {
    __typename: 'ComponentTwoColumnContentListBody',
    json: {
      data: {},
      content: [
        {
          data: {},
          content: [
            {
              data: {},
              marks: [],
              value:
                'Each ASCD annual report covers a fiscal year (September through August).  Please ',
              nodeType: 'text',
            },
            {
              data: {
                uri: '/contact',
              },
              content: [
                {
                  data: {},
                  marks: [
                    {
                      type: 'bold',
                    },
                  ],
                  value: 'contact us ',
                  nodeType: 'text',
                },
              ],
              nodeType: 'hyperlink',
            },
            {
              data: {},
              marks: [],
              value: 'for additional archived reports. ',
              nodeType: 'text',
            },
          ],
          nodeType: 'paragraph',
        },
        {
          data: {},
          content: [
            {
              data: {},
              marks: [],
              value: '',
              nodeType: 'text',
            },
          ],
          nodeType: 'paragraph',
        },
      ],
      nodeType: 'document',
    },
  },
  listItem: {
    __typename: 'ComponentTwoColumnContentListListItemCollection',
    items: [
      {
        __typename: 'ComponentListItem',
        title: '2021: Supporting the Whole Child and the Whole Educator',
        body: 'Our response to the overwhelming stress reported by educators everywhere.',
        thumbnail: {
          __typename: 'Image',
          alternate:
            '2021 ASCD Annual Report cover image of a large red stylized lower-case letter "a" on a white background. In the top left corner in much smaller font is the ASCD logo and in the top right corner the words "2021 Annual Report". ',
          title: '2021 ASCD Annual Report Cover',
          caption: null,
          imgSrc: null,
          imageContentful: null,
          imageBynder: [
            {
              archive: 0,
              brandId: '2154F1D0-CD10-4BE9-8B8E3480E8546AB1',
              copyright: null,
              dateCreated: '2022-03-11T21:22:12Z',
              dateModified: '2022-03-11T21:22:12Z',
              datePublished: '2022-03-11T21:21:45Z',
              description: null,
              extension: ['jpg'],
              fileSize: 55629,
              height: 560,
              id: '6431C5F1-DE57-4A11-956BDFE3AF840DFA',
              isPublic: 0,
              limited: 0,
              name: '2021 Annual Report Cover',
              orientation: 'landscape',
              original: null,
              thumbnails: {
                webimage:
                  'https://library.ascd.org/m/dc9f579433263e2/webimage-2021-Annual-Report-Cover.jpg',
                thul: 'https://library.ascd.org/m/dc9f579433263e2/thul-2021-Annual-Report-Cover.jpg',
                mini: 'https://library.ascd.org/m/dc9f579433263e2/mini-2021-Annual-Report-Cover.jpg',
              },
              type: 'image',
              watermarked: 0,
              width: 735,
              videoPreviewURLs: [],
              src: 'https://library.ascd.org/m/dc9f579433263e2/webimage-2021-Annual-Report-Cover.jpg',
            },
          ],
        },
        url: 'https://library.ascd.org/m/7565440b3dfbaed3/original/ASCD-2021-Annual-Report.pdf',
      },
      {
        __typename: 'ComponentListItem',
        title: "2020: ASCD's Response to a New Reality",
        body: 'The months marked by this annual report were like no other.',
        thumbnail: {
          __typename: 'Image',
          alternate: '2020 ASCD Annual Report cover',
          title: '2020 ASCD Annual Report',
          caption: null,
          imgSrc: null,
          imageContentful: null,
          imageBynder: [
            {
              id: '25B6252D-907A-4A32-8BE7E47DC2DDA962',
              src: 'https://library.ascd.org/m/25cff75b8f59a72c/webimage-ASCD-2020-Annual-Report-Cover-Image.jpg',
              name: 'ASCD 2020 Annual Report Cover Image',
              type: 'image',
              width: 392,
              height: 479,
              archive: 0,
              brandId: '2154F1D0-CD10-4BE9-8B8E3480E8546AB1',
              limited: 0,
              fileSize: 88551,
              isPublic: 0,
              original: null,
              copyright: null,
              extension: ['jpg'],
              thumbnails: {
                mini: 'https://library.ascd.org/m/25cff75b8f59a72c/mini-ASCD-2020-Annual-Report-Cover-Image.jpg',
                thul: 'https://library.ascd.org/m/25cff75b8f59a72c/thul-ASCD-2020-Annual-Report-Cover-Image.jpg',
                webimage:
                  'https://library.ascd.org/m/25cff75b8f59a72c/webimage-ASCD-2020-Annual-Report-Cover-Image.jpg',
              },
              dateCreated: '2021-10-21T19:10:45Z',
              description: null,
              orientation: 'portrait',
              watermarked: 0,
              dateModified: '2021-10-21T19:10:45Z',
              datePublished: '2021-10-21T19:09:20Z',
              videoPreviewURLs: [],
            },
          ],
        },
        url: 'https://files.ascd.org/pdfs/general/2020_ascd_annual_report.pdf',
      },
      {
        __typename: 'ComponentListItem',
        title: '2019: Learn. Teach. Lead.',
        body: 'Reaffirming our mission to support a whole child approach to education.',
        thumbnail: {
          __typename: 'Image',
          alternate: '2019 ASCD Annual Report Cover',
          title: '2019 ASCD Annual Report Cover',
          caption: null,
          imgSrc: null,
          imageContentful: null,
          imageBynder: [
            {
              id: 'E205FC10-225C-4B38-912BCD5CAFE319C3',
              src: 'https://library.ascd.org/m/554aace5afa4906b/webimage-ASCD-2019-Annual-Report-Cover-Image.jpg',
              name: 'ASCD 2019 Annual Report Cover Image',
              type: 'image',
              width: 250,
              height: 478,
              archive: 0,
              brandId: '2154F1D0-CD10-4BE9-8B8E3480E8546AB1',
              limited: 0,
              fileSize: 9102,
              isPublic: 0,
              original: null,
              copyright: null,
              extension: ['jpg'],
              thumbnails: {
                mini: 'https://library.ascd.org/m/554aace5afa4906b/mini-ASCD-2019-Annual-Report-Cover-Image.jpg',
                thul: 'https://library.ascd.org/m/554aace5afa4906b/thul-ASCD-2019-Annual-Report-Cover-Image.jpg',
                webimage:
                  'https://library.ascd.org/m/554aace5afa4906b/webimage-ASCD-2019-Annual-Report-Cover-Image.jpg',
              },
              dateCreated: '2021-10-21T19:10:45Z',
              description: null,
              orientation: 'portrait',
              watermarked: 0,
              dateModified: '2021-10-21T19:10:45Z',
              datePublished: '2021-10-21T19:09:20Z',
              videoPreviewURLs: [],
            },
          ],
        },
        url: 'https://files.ascd.org/pdfs/general/2019_ascd_annual_report.pdf',
      },
      {
        __typename: 'ComponentListItem',
        title: '2018: 75 Years of Excellence',
        body: '75 years of excellence in learning, teaching, and leading.',
        thumbnail: {
          __typename: 'Image',
          alternate: '2018 ASCD Annual Report Cover',
          title: '2018 ASCD Annual Report Cover',
          caption: null,
          imgSrc: null,
          imageContentful: null,
          imageBynder: [
            {
              id: 'D2A84044-AC18-47F7-9E609DEFE5E55229',
              src: 'https://library.ascd.org/m/6d041f7aa68de47/webimage-ASCD-2018-Annual-Report-Cover-Image.jpg',
              name: 'ASCD 2018 Annual Report Cover Image',
              type: 'image',
              width: 250,
              height: 415,
              archive: 0,
              brandId: '2154F1D0-CD10-4BE9-8B8E3480E8546AB1',
              limited: 0,
              fileSize: 71520,
              isPublic: 0,
              original: null,
              copyright: null,
              extension: ['jpg'],
              thumbnails: {
                mini: 'https://library.ascd.org/m/6d041f7aa68de47/mini-ASCD-2018-Annual-Report-Cover-Image.jpg',
                thul: 'https://library.ascd.org/m/6d041f7aa68de47/thul-ASCD-2018-Annual-Report-Cover-Image.jpg',
                webimage:
                  'https://library.ascd.org/m/6d041f7aa68de47/webimage-ASCD-2018-Annual-Report-Cover-Image.jpg',
              },
              dateCreated: '2021-10-21T19:10:45Z',
              description: null,
              orientation: 'portrait',
              watermarked: 0,
              dateModified: '2021-10-21T19:10:45Z',
              datePublished: '2019-03-14T11:45:05Z',
              videoPreviewURLs: [],
            },
          ],
        },
        url: 'https://files.ascd.org/pdfs/general/2018_ascd_annual_report.pdf',
      },
      {
        __typename: 'ComponentListItem',
        title: '2017: Activate, Educate.',
        body: "Empowering educators with high caliber resources to ensure students' success.",
        thumbnail: {
          __typename: 'Image',
          alternate: '2017 ASCD Annual Report Cover Image',
          title: '2017 ASCD Annual Report Cover Image',
          caption: null,
          imgSrc: null,
          imageContentful: null,
          imageBynder: [
            {
              id: 'B8099032-1765-4E45-AF5FDE4357CF5984',
              src: 'https://library.ascd.org/m/5615fb7c6777d192/webimage-ASCD-2017-Annual-Report-Cover-Image.jpg',
              name: 'ASCD 2017 Annual Report Cover Image',
              type: 'image',
              width: 250,
              height: 415,
              archive: 0,
              brandId: '2154F1D0-CD10-4BE9-8B8E3480E8546AB1',
              limited: 0,
              fileSize: 37515,
              isPublic: 0,
              original: null,
              copyright: null,
              extension: ['jpg'],
              thumbnails: {
                mini: 'https://library.ascd.org/m/5615fb7c6777d192/mini-ASCD-2017-Annual-Report-Cover-Image.jpg',
                thul: 'https://library.ascd.org/m/5615fb7c6777d192/thul-ASCD-2017-Annual-Report-Cover-Image.jpg',
                webimage:
                  'https://library.ascd.org/m/5615fb7c6777d192/webimage-ASCD-2017-Annual-Report-Cover-Image.jpg',
              },
              dateCreated: '2021-10-21T19:10:45Z',
              description: null,
              orientation: 'portrait',
              watermarked: 0,
              dateModified: '2021-10-21T19:10:45Z',
              datePublished: '2021-10-21T19:09:20Z',
              videoPreviewURLs: [],
            },
          ],
        },
        url: 'https://files.ascd.org/pdfs/general/2017_ascd_annual_report.pdf',
      },
    ],
  },
}
