export const gridMock = {
  gridItems: [
    {
      __typename: 'ComponentGridItem',
      title: 'Avis Williams',
      titleAlignment: null,
      body: 'Board President\n\nSuperintendent, NOLA Public Schools\n\nTerm: July 1, 2020–June 30, 2024',
      bodyAlignment: null,
      link: '/people/avis-williams',
      cta: null,
      buttonLink: null,
      thumbnail: {
        __typename: 'Image',
        alternate: 'Avis Williams - ASCD Board of Directors',
        title: 'Avis Williams - ASCD Board of Directors',
        caption: null,
        imgSrc: null,
        imageContentful: null,
        imageBynder: [
          {
            id: '81523CC3-8288-4960-8DB99438F0ED3A57',
            src: 'https://library.ascd.org/m/1f0f6a0afba137ce/webimage-avis_williams.jpg',
            name: 'avis_williams',
            type: 'image',
            width: 1252,
            height: 1481,
            archive: 0,
            brandId: '2154F1D0-CD10-4BE9-8B8E3480E8546AB1',
            limited: 0,
            fileSize: 587199,
            isPublic: 0,
            original: null,
            copyright: null,
            extension: ['jpg'],
            thumbnails: {
              mini: 'https://library.ascd.org/m/1f0f6a0afba137ce/mini-avis_williams.jpg',
              thul: 'https://library.ascd.org/m/1f0f6a0afba137ce/thul-avis_williams.jpg',
              webimage:
                'https://library.ascd.org/m/1f0f6a0afba137ce/webimage-avis_williams.jpg',
            },
            dateCreated: '2021-06-17T02:20:32Z',
            description: null,
            orientation: 'portrait',
            watermarked: 0,
            dateModified: '2021-06-17T02:20:32Z',
            datePublished: '2021-06-17T02:18:47Z',
            videoPreviewURLs: [],
          },
        ],
      },
      linkButton: null,
    },
    {
      __typename: 'ComponentGridItem',
      title: 'Matthew Mingle',
      titleAlignment: null,
      body: 'Board Vice President\n\nSuperintendent, Warren Township Schools\n\nTerm: July 1, 2018–June 30, 2023',
      bodyAlignment: null,
      link: '/people/matthew-mingle',
      cta: null,
      buttonLink: null,
      thumbnail: {
        __typename: 'Image',
        alternate: 'Matthew Mingle - ASCD Board of Directors',
        title: 'Matthew Mingle - ASCD Board of Directors',
        caption: null,
        imgSrc: null,
        imageContentful: null,
        imageBynder: [
          {
            id: '0E176502-3D8D-41BC-BB49323D96416003',
            src: 'https://library.ascd.org/m/3962261f71d6a149/webimage-matt_mingle.jpg',
            name: 'matt_mingle',
            type: 'image',
            width: 5184,
            height: 3456,
            archive: 0,
            brandId: '2154F1D0-CD10-4BE9-8B8E3480E8546AB1',
            limited: 0,
            fileSize: 7848712,
            isPublic: 0,
            original: null,
            copyright: null,
            extension: ['jpg'],
            thumbnails: {
              mini: 'https://library.ascd.org/m/3962261f71d6a149/mini-matt_mingle.jpg',
              thul: 'https://library.ascd.org/m/3962261f71d6a149/thul-matt_mingle.jpg',
              webimage:
                'https://library.ascd.org/m/3962261f71d6a149/webimage-matt_mingle.jpg',
            },
            dateCreated: '2021-09-16T15:00:50Z',
            description: null,
            orientation: 'landscape',
            watermarked: 0,
            dateModified: '2021-09-16T15:00:50Z',
            datePublished: '2021-09-16T14:59:48Z',
            videoPreviewURLs: [],
          },
        ],
      },
      linkButton: null,
    },
  ],
  title: '2022–2023 ASCD Board of Directors',
  gridBody: {
    __typename: 'ComponentGridBody',
    json: {
      data: {},
      content: [
        {
          data: {},
          content: [
            {
              data: {},
              marks: [],
              value:
                'The ASCD Board of Directors comprises members elected by the general membership who serve four-year terms and appointed members who may serve up to four years. ',
              nodeType: 'text',
            },
          ],
          nodeType: 'paragraph',
        },
      ],
      nodeType: 'document',
    },
  },
  bodyCentered: null,
  layout: 'three-col-avatar',
  pageId: 'governance',
}
