export const invoice = {
  orderNumber: 11111111111,
  invoiceNumber: 222222222,
  poNumber: 333333333,
  invoiceDate: '?',
  emailId: 'email@email.com',
  shipName: 'Ship Name',
  shippingAddress1: 'ship St',
  shippingAddress2: 'Ship Room',
  shippingCity: 'Ship City',
  shippingState: 'TX',
  shippingCountry: 'US',
  shippingZip: '12345',
  orderDate: '?',
  billingName: 'Bill Name',
  billingAddress1: 'Bill St',
  billingAddress2: 'Bill Room',
  billingCity: 'Bill City',
  billingState: 'NY',
  billingCountry: 'US',
  billingZip: '54321',
  fulFillStatus: '',
  fulFillDate: '?',
  shipmethod: '',
  shipDate: '?',
  token: '',
  roleCategory: 'Principal',
  school: 'skool',
  district: 'school district',
  creditCardLast4Digits: '1234',
  completionDate: '2022-05-30T14:53:11Z',
  cardType: 'Visa',
  paymentMethod: 'CreditCard',
  paymentStatus: 'Paid',
  tax: 6,
  shipPrice: 1,
  total: 95,
  productOrders: [
    {
      productCode: '111111111',
      purchaseItem: 'thing',
      unitPrice: 100,
      discount: 5,
      productTotal: 95,
      quantity: 3,
    },
  ],
}
