name: 02 (Auto) Pull Request Build Stage

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [stage]
    paths-ignore:
      - '.github/**'
      - '.githooks/**'
      - '**.md'
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Setup .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.RELEASE_WORKFLOW_TOKEN }}" > ~/.npmrc

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        id: deps
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

      # Creating .env file for build
      - name: Create .env file
        run: |
          touch .env
          echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> .env
          echo MYSQL_HOST=${{ secrets.MYSQL_HOST }} >> .env
          echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env
          echo MYSQL_PORT=${{ secrets.MYSQL_PORT }} >> .env
          echo MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} >> .env
          echo MYSQL_DATABASE_MDB=${{ secrets.MYSQL_DATABASE }} >> .env
          echo MYSQL_HOST_MDB=${{ secrets.MYSQL_HOST }} >> .env
          echo MYSQL_PASSWORD_MDB=${{ secrets.MYSQL_PASSWORD }} >> .env
          echo MYSQL_PORT_MDB=${{ secrets.MYSQL_PORT }} >> .env
          echo MYSQL_USERNAME_MDB=${{ secrets.MYSQL_USERNAME }} >> .env
          echo NEXT_PUBLIC_ALGOLIA_APP_ID=${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }} >> .env
          echo NEXT_PUBLIC_ALGOLIA_INDEX_ID=${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_ID }} >> .env
          echo NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY }} >> .env
          echo NEXT_PUBLIC_ALGOLIA_WRITE_API_KEY=${{ secrets.NEXT_PUBLIC_ALGOLIA_WRITE_API_KEY }} >> .env
          echo NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }} >> .env
          echo NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=${{ secrets.NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT }} >> .env
          echo NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN }} >> .env
          echo NEXT_PUBLIC_CONTENTFUL_SPACE_ID=${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }} >> .env
          echo NEXT_PUBLIC_COOKIE_API_URL=${{ secrets.NEXT_PUBLIC_COOKIE_API_URL }} >> .env
          echo NEXT_PUBLIC_WITSBY_URL=${{ secrets.NEXT_PUBLIC_WITSBY_URL }} >> .env
          echo NEXT_PUBLIC_PIANO_API_BASE_URL=${{ secrets.NEXT_PUBLIC_PIANO_API_BASE_URL }} >> .env
          echo NEXT_PUBLIC_PIANO_API_KEY=${{ secrets.NEXT_PUBLIC_PIANO_API_KEY }} >> .env
          echo NEXT_PUBLIC_PIANO_APP_ID=${{ secrets.NEXT_PUBLIC_PIANO_APP_ID }} >> .env
          echo NEXT_PUBLIC_PIANO_JS_ENDPOINT=${{ secrets.NEXT_PUBLIC_PIANO_JS_ENDPOINT }} >> .env
          echo NEXT_PUBLIC_PIANO_PRIVATE_KEY=${{ secrets.NEXT_PUBLIC_PIANO_PRIVATE_KEY }} >> .env
          echo NEXT_PUBLIC_SECRET_SNIPCART_API_KEY=${{ secrets.NEXT_PUBLIC_SECRET_SNIPCART_API_KEY }} >> .env
          echo NEXT_PUBLIC_SNIPCART_JS_DATA_API_KEY=${{ secrets.NEXT_PUBLIC_SNIPCART_JS_DATA_API_KEY }} >> .env
          echo NEXT_PUBLIC_SNIPCART_ORDER_VALIDATION_BASE_URL=${{ secrets.NEXT_PUBLIC_SNIPCART_ORDER_VALIDATION_BASE_URL }} >> .env
          echo NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }} >> .env
          echo NEXT_PUBLIC_WISTIA_API_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_WISTIA_API_ACCESS_TOKEN }} >> .env
          echo NEXT_PUBLIC_BASE64_ENCODED_ORDERS_SNIPCART_SECRET=${{ secrets.NEXT_PUBLIC_BASE64_ENCODED_ORDERS_SNIPCART_SECRET }} >> .env
          echo NEXT_PUBLIC_YES_ELECTIONS_ASCD_CUSTOMER_ID=${{ secrets.NEXT_PUBLIC_YES_ELECTIONS_ASCD_CUSTOMER_ID }} >> .env
          echo NEXT_PUBLIC_YES_ELECTIONS_URI=${{ secrets.NEXT_PUBLIC_YES_ELECTIONS_URL }} >> .env
          echo NEXT_STATIC_BUILD_LIMIT=${{ secrets.NEXT_STATIC_BUILD_LIMIT }} >> .env
          echo STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} >> .env
          echo NEXT_PUBLIC_REALM_APP_BASE_URL=${{ secrets.NEXT_PUBLIC_REALM_APP_BASE_URL }} >> .env
          echo NEXT_PUBLIC_REALM_APP_ID=${{ secrets.NEXT_PUBLIC_REALM_APP_ID }} >> .env
          echo NEXT_PUBLIC_REALM_APP_KEY=${{ secrets.NEXT_PUBLIC_REALM_APP_KEY }} >> .env
          echo NEXT_PUBLIC_SAMPLES_TRACE_RATE=${{ secrets.NEXT_PUBLIC_SAMPLES_TRACE_RATE}} >> .env
          echo SENTRY_ORG=${{ secrets.SENTRY_ORG }} >> .env
          echo SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }} >> .env
          echo SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} >> .env
          echo NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }} >> .env
          cat .env

      - name: Run build
        id: build
        run: npm run build
